Transform: AWS::Serverless-2016-10-31

Resources:
  CreateUserHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CreateUser.handler
      CodeUri: build
      Runtime: nodejs14.x
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /users
            Method: POST
Outputs:
  ApiGatewayURL:
    Value: !GetAtt ServerlessHttpApi.ApiEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-url"
